on: push
name: Build and publish
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build
        uses: framer/bridge@master
        with:
          args: build <your-project-path.framerx>

      - name: Publish
        uses: framer/bridge@master
        env:
          FRAMER_TOKEN: ${{ secrets.FRAMER_TOKEN }}
        with:
          args: publish <your-project-path.framerfx> --yes
